<?xml version="1.0"?>
<robot name="jupiter" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find jupiter)/description/jupiter_properties.urdf.xacro" />
  <xacro:include filename="$(find jupiter)/description/base.urdf.xacro" />
  <xacro:include filename="$(find jupiter)/description/wheel.urdf.xacro" />
  <xacro:include filename="$(find jupiter)/description/skid_steer.urdf.xacro" />
    
  <xacro:include filename="$(find jupiter)/sensors/imu.urdf.xacro" />
  <xacro:include filename="$(find jupiter)/sensors/ldlidar.urdf.xacro" />
  <xacro:include filename="$(find jupiter)/sensors/camera.urdf.xacro" />

    
  <xacro:base 
    length="${base_length}" 
    width="${base_width}" 
    height="${base_height}" 
    mass="${base_mass}"
    wheel_radius="${wheel_radius}"
    wheel_pos_z="${wheel_pos_z}"
  />

  <xacro:wheel 
    side="front_left"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${wheel_pos_x}" 
    pos_y="${wheel_pos_y}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
  />

  <xacro:wheel 
    side="front_right"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${wheel_pos_x}" 
    pos_y="${-wheel_pos_y}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
  />
  <xacro:wheel 
    side="rear_left"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${-wheel_pos_x}" 
    pos_y="${wheel_pos_y}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
  />

  <xacro:wheel 
    side="rear_right"
    radius="${wheel_radius}" 
    width="${wheel_width}" 
    pos_x="${-wheel_pos_x}" 
    pos_y="${-wheel_pos_y}" 
    pos_z="${wheel_pos_z}" 
    mass="${wheel_mass}"
  />
  
  <xacro:imu/>

  <xacro:ldlidar/>

  <xacro:camera/>
  
  <xacro:diff_drive_controller
    wheel_separation="${wheel_pos_y * 2}"
    wheel_radius="${wheel_radius}"
    wheel_torque="${wheel_torque}"
  />
</robot>